// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evggmwlsmriivvrjfuvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Z2dtd2xzbXJpaXZ2cmpmdXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODk5OTksImV4cCI6MjA2NjA2NTk5OX0.oLAXc3_S6xzzLfsXI_pMJWZZArO9LB1LEZexGKnBST0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);